Update patch set 2
Patch Set 2: Code-Review+1

We need to stage a change to fix:
ERROR: No recipes available for:
  /w/workspace/ci-platform-AGL-repo-verify-CIB-intel-corei7-64/repoclone/meta-agl-demo/recipes-qt/qt5/qtwayland-native_%.bbappend
Parsing of 2170 .bb files complete (2144 cached, 26 parsed). 2893 targets, 355 skipped, 0 masked, 0 errors.

Likely it is enough to remove the bbappend.

Patch-set: 2