fix(jellyfish_9.99.1.xml): change meta-python2 repo url
We can only git clone meta-python2 via
https://git.openembedded.org/meta-python2 and
git://git.openembedded.org/meta-python2,

while git clone https://git.openembedded.org/meta-python2.git or
git://git.openembedded.org/meta-python2.git will report a not found
error.

In the other side, repo manifest always appends a suffix “.git”
to a repo assumes the upstream is a forest of bare Git repositories.

Refer:
https://gerrit.googlesource.com/git-repo/+/master/docs/manifest-format.md#element-project

Although this github meta-python2 seems not a official mirror repo,  it
can work at this moment.

error log:

ubuntu@ubuntu:/newdisk/AGL-TEST/agl-8.99.2$ repo sync meta-python2

Initializing project meta-python2 ...
fatal: repository 'https://git.openembedded.org/meta-python2.git/' not found
error: Cannot fetch meta-python2

Bug-AGL: SPEC-3460

Change-Id: I66554627144f8665321e060a71e3f60874048c6a
Signed-off-by: Li, Xiaoming <lixm.fnst@cn.fujitsu.com>