Update patch set 1
Patch Set 1:

Need to check:
NOTE: Running task 3289 of 6383 (/w/workspace/ci-platform-AGL-repo-verify-CIB-intel-corei7-64/repoclone/poky/meta/recipes-kernel/linux-libc-headers/linux-libc-headers_4.8.bb:do_packagedata)
ERROR: linux-firmware-1_0.0+gitAUTOINC+bf04291309-r0 do_package: QA Issue: linux-firmware-ibt-license is listed in PACKAGES multiple times, this leads to packaging errors. [packages-list]
ERROR: linux-firmware-1_0.0+gitAUTOINC+bf04291309-r0 do_package: QA Issue: linux-firmware-ibt-11-5 is listed in PACKAGES multiple times, this leads to packaging errors. [packages-list]

Patch-set: 1